name: iOS Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to TestFlight
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Fastlane
        run: |
          cd ios
          bundle install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Deploy to TestFlight
        env:
          APPLE_APP_ID: ${{ secrets.APPLE_APP_ID }}
        run: |
          cd ios
          bundle exec fastlane beta 