name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to TestFlight
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Decode App Store Connect API key
        run: echo "${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}" > AuthKey.p8

      - name: Install dependencies
        run: yarn install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Install Fastlane
        run: |
          bundle install

      - name: Deploy to TestFlight
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          bundle exec fastlane beta